pool: 
  vmImage: windows-latest
trigger: 
  - main
variables: 
  buildConfiguration: Release
  buildPlatform: "Any CPU"
  solution: Lochi.Portfolio/Server/Lochi.Portfolio.Server.csproj
jobs: 
  job: Prepare
  steps: 
    - 
      task: NodeTool@0
    - 
      task: NuGetToolInstaller@1
    - 
      displayName: "Install .NET Core SDK"
      inputs: 
        includePreviewVersions: true
        performMultiLevelLookup: true
        version: 6.0.x
      task: UseDotNet@2
    - 
      displayName: Restore
      inputs: 
        command: restore
        projects: $(solution)
      task: DotNetCoreCLI@2
    - 
      inputs: 
        arguments: "--configuration $(buildConfiguration)"
        command: build
        projects: $(solution)
      task: DotNetCoreCLI@2
    - 
      displayName: "Archive files"
      inputs: 
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        archiveType: zip
        includeRootFolder: false
        replaceExistingArchive: true
        rootFolderOrFile: Lochi.Portfolio/Server/bin/Release/net6.0/publish
      task: ArchiveFiles@2
    - 
      artifact: drop
      upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    - 
      deployment: VMDeploy
      displayName: web
      environment: 
        name: vm
        resourceName: lochi
        resourceType: VirtualMachine
        tags: lochi.destroyer
      strategy: 
        runOnce: 
          deploy: 
            steps: 
              - 
                script: "echo my first deployment"

